// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.xkcoding.grpc.protocol;

public interface DemoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
