// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.xkcoding.grpc.protocol;

public interface DemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoRequest)
    com.google.protobuf.MessageOrBuilder {
}
