server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    hikari:
      username: root
      password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
mybatis-plus:
  global-config:
    # 关闭banner
    banner: false